theme: jekyll-theme-cayman
title: 新哥博客
author: fang岸新
subtitle:  下雨了怎么办，我好想你，不敢给你打电话，怕你被雷劈。
description: 下雨了怎么办，我好想你，不敢给你打电话，怕你被雷劈。
valine_comment:
  enable: true
# app_id
  leancloud_appid: QfRU6DYFWzDirtwuiLlhyXtb-gzGzoHsz
# app_key
  leancloud_appkey: WOcr9PrBAotMgjLlx00TmbDm
# placeholde
  placeholder: “Just go go"
--------------------- 
作者：WildGr4ss 
来源：CSDN 
原文：https://blog.csdn.net/WildGr4ss/article/details/83552478 
版权声明：本文为博主原创文章，转载请附上博文链接！
